describe('Article creation and deletion flow', () => {
  let user;
  let article;

  before(() => {
    cy.task('generateUser').then((generatedUser) => {
      user = generatedUser;
      article = {
        title: `Test article ${Date.now()}`,
        description: 'Autogenerated description',
        body: 'This is the body of an article created via Cypress test.',
        tagList: ['cypress', 'test']
      };

      cy.request('POST', 'https://api.realworld.io/api/users', {
        user: {
          email: user.email,
          username: user.username,
          password: user.password
        }
      });
    });
  });

  it('should create a new article', () => {
    cy.login(user.email, user.password);
    cy.visit('/');

    cy.contains('New Article').click();

    cy.get('input[placeholder="Article Title"]').type(article.title);
    cy.get('input[placeholder*="about"]').type(article.description);
    cy.get('textarea[placeholder="Write your article"]').type(article.body);
    cy.get('input[placeholder="Enter tags"]').type('cypress{enter}');
    cy.contains('Publish Article').click();

    cy.url().should('include', '/article/');
    cy.contains(article.title).should('be.visible');
    cy.contains(article.body).should('be.visible');
  });

  it('should delete the created article', () => {
    cy.login(user.email, user.password);
    cy.createArticle(article).then((slug) => {
      cy.visit(`/article/${slug}`);
      cy.contains('Delete Article').click();

      cy.url().should('eq', `${Cypress.config('baseUrl')}`);
      cy.visit(`/article/${slug}`);
      cy.contains('Page not found').should('exist');
    });
  });
});
